[package]
name = "ttf_word_wrap"
version = "0.1.0"
authors = ["Benjamin Halsted <bg@hlstd.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ttf-parser = "0.11.0"
